const dayWords = {
    1: [
        { word: "assure", meaning: "확신시키다, 보장하다" },
        { word: "genuine", meaning: "진짜의" },
        { word: "conclusive", meaning: "결정적인, 확실한" },
        { word: "investigate", meaning: "조사하다" },
        { word: "eliminate", meaning: "없애다, 제거하다" },
        { word: "paradox", meaning: "모순된 말" },
        { word: "particular", meaning: "특정한, 특별한" },
        { word: "unsophisticated", meaning: "단순한, 복잡하지 않은" },
        { word: "postulate", meaning: "(자명한 일로) 가정하다, 주장하다" },
        { word: "successively", meaning: "잇따라서" },
        { word: "promptly", meaning: "신속하게, 즉시" },
        { word: "contour", meaning: "윤곽, 외형" },
        { word: "pervasive", meaning: "퍼지는, 만연하는" },
        { word: "annihilate", meaning: "전멸시키다" },
        { word: "sleek", meaning: "매끄러운" },
        { word: "perfect", meaning: "개선하다, 완벽하게 하다" },
        { word: "superficially", meaning: "표면적으로" },
        { word: "dominant", meaning: "우세한, 주요한" },
        { word: "malleable", meaning: "두들겨 펼 수 있는" },
        { word: "invoke", meaning: "빌다, 기원하다" },
        { word: "subdue", meaning: "정복하다" },
        { word: "impressive", meaning: "인상적인, 대단한" },
        { word: "justified", meaning: "정당한" },
        { word: "aftermath", meaning: "여파, 결과" },
        { word: "inhabit", meaning: "거주하다" },
        { word: "no wonder", meaning: "놀랄 일이 아닌" },
        { word: "exclude", meaning: "차단하다, 배제하다" },
        { word: "strenuous", meaning: "격렬한, 힘든" },
        { word: "account for", meaning: "(이유 등을) 설명하다, (부분∙비율을) 차지하다, 원인이 되다" },
        { word: "compensate for", meaning: "~을 보상하다, 상쇄하다" },
        { word: "depend on", meaning: "~에 의존하다, 의지하다" },
        { word: "pillar", meaning: "기둥" },
        { word: "extant", meaning: "현존하는" },
        { word: "stunted", meaning: "발달이 저해된, 성장을 멈춘" },
        { word: "encroachment", meaning: "잠식, 침입" },
        { word: "afford", meaning: "주다, 제공하다" },
        { word: "conversely", meaning: "반대로" },
        { word: "solid", meaning: "확고한, 견고한" },
        { word: "pinpoint", meaning: "(위치 등을) 정확히 찾아내다, 정확한" },
        { word: "deliberate", meaning: "의도적인, 계획적인, 신중한" },
        { word: "substantiate", meaning: "입증하다" },
        { word: "magnify", meaning: "확대하다" },
        { word: "neglect", meaning: "무시하다, (해야 할 일을) 하지 않다, 잊다" },
        { word: "prominent", meaning: "눈에 띄는, 중요한" },
        { word: "unrivaled", meaning: "비할 데 없는" },
        { word: "mean", meaning: "의미하다, 나타내다, 평균" },
        { word: "conjunction", meaning: "결합" },
        { word: "recall", meaning: "상기하다, 생각해내다" },
        { word: "ascend", meaning: "올라가다" },
        { word: "replenish", meaning: "보충하다" }
    ],
    2: [
        { word: "conspicuous", meaning: "뚜렷한" },
        { word: "elaborately", meaning: "정교하게" },
        { word: "implausible", meaning: "믿기 어려운" },
        { word: "comparative", meaning: "상대적인" },
        { word: "stamp out", meaning: "근절하다" },
        { word: "drastically", meaning: "극심하게" },
        { word: "specify", meaning: "명시하다" },
        { word: "optimize", meaning: "최대한 잘 활용하다" },
        { word: "prolific", meaning: "다산의, 풍부한" },
        { word: "endure", meaning: "견디다, 지속하다" },
        { word: "conventionally", meaning: "관례적으로" },
        { word: "grow accustomed to", meaning: "~에 익숙해지다" },
        { word: "susceptible to", meaning: "~에 걸리기 쉬운, 영향 받기 쉬운" },
        { word: "boom", meaning: "갑자기 번창하다" },
        { word: "expansive", meaning: "넓은, 광대한" },
        { word: "plug", meaning: "메우다, 채우다" },
        { word: "autonomous", meaning: "자율적인" },
        { word: "allocate", meaning: "할당하다, 배정하다" },
        { word: "evaluate", meaning: "평가하다" },
        { word: "virtually", meaning: "사실상, 거의" },
        { word: "stagnation", meaning: "침체" },
        { word: "landscape", meaning: "풍경" },
        { word: "elucidate", meaning: "(명료하게) 설명하다" },
        { word: "innate", meaning: "선천적인" },
        { word: "regard", meaning: "생각하다, 간주하다, 관심" },
        { word: "abrupt", meaning: "갑작스러운" },
        { word: "conceivable", meaning: "생각할 수 있는" },
        { word: "supplant", meaning: "대체하다" },
        { word: "entail", meaning: "(필연적으로) 수반하다, 일으키다, 필요로 하다" },
        { word: "obsession with", meaning: "~에 대한 집착" },
        { word: "monotonous", meaning: "단조로운, 지루한" },
        { word: "supremacy", meaning: "우위" },
        { word: "contemporary", meaning: "현대의, 동시대의" },
        { word: "sufficiently", meaning: "충분히" },
        { word: "comprehensive", meaning: "종합적인" },
        { word: "emanate", meaning: "(향기∙빛 등이) 나다" },
        { word: "colossal", meaning: "거대한, 엄청난" },
        { word: "depict", meaning: "묘사하다" },
        { word: "engrave", meaning: "새기다" },
        { word: "ravage", meaning: "파괴하다" },
        { word: "fluctuation", meaning: "변동" },
        { word: "intrigue", meaning: "흥미를 끌다" },
        { word: "heterogeneous", meaning: "잡다한, 혼성의" },
        { word: "slight", meaning: "하찮은, 경미한" },
        { word: "diffuse", meaning: "퍼뜨리다" },
        { word: "unprecedented", meaning: "전례 없는, 새로운" },
        { word: "capture", meaning: "붙잡다" },
        { word: "decline", meaning: "쇠퇴, 쇠약, 줄다, 감소하다, 거절하다" },
        { word: "sporadically", meaning: "이따금씩" },
        { word: "discrepancy", meaning: "불일치" }
    ],
    3: [
        { word: "vigorous", meaning: "강건한, 활기찬, (작용∙효력 등이) 강력한" },
        { word: "status", meaning: "지위, 위신" },
        { word: "devastating", meaning: "파괴적인" },
        { word: "trigger", meaning: "일으키다" },
        { word: "apparent", meaning: "분명한, 외관상의" },
        { word: "denote", meaning: "나타내다, 표시하다" },
        { word: "pore", meaning: "작은 구멍, 자세히 보다, 응시하다" },
        { word: "reveal", meaning: "밝히다, 드러내다" },
        { word: "rigorous", meaning: "엄격한, (기후 등이) 혹독한" },
        { word: "manifestation", meaning: "징후" },
        { word: "vast", meaning: "광대한, 거대한" },
        { word: "compulsory", meaning: "의무적인, 강제적인" },
        { word: "tentativeness", meaning: "망설임" },
        { word: "prior", meaning: "이전의" },
        { word: "fine-tune", meaning: "미세하게 조정하다" },
        { word: "miniature", meaning: "소형의" },
        { word: "conjecture", meaning: "추측" },
        { word: "migrate", meaning: "이주하다" },
        { word: "enthusiastic", meaning: "열광적인" },
        { word: "experimental", meaning: "시험적인" },
        { word: "largely", meaning: "대부분" },
        { word: "attempt", meaning: "시도하다" },
        { word: "ensure", meaning: "보장하다" },
        { word: "succession", meaning: "연속" },
        { word: "sturdy", meaning: "튼튼한" },
        { word: "contradictory", meaning: "모순되는" },
        { word: "emphasize", meaning: "강조하다" },
        { word: "bombard", meaning: "폭격하다, 공격하다" },
        { word: "alternate", meaning: "번갈아 일어나다" },
        { word: "subsidiary", meaning: "부수적인" },
        { word: "reluctant", meaning: "꺼리는" },
        { word: "cast about", meaning: "찾아다니다" },
        { word: "vow", meaning: "서약, 맹세" },
        { word: "traditionally", meaning: "통상적으로, 관습적으로" },
        { word: "drain", meaning: "물을 빼내다" },
        { word: "setback", meaning: "패배" },
        { word: "legendary", meaning: "유명한, 전설적인" },
        { word: "contention", meaning: "논쟁" },
        { word: "embed", meaning: "박아 넣다" },
        { word: "commission", meaning: "의뢰하다" },
        { word: "convert", meaning: "바꾸다" },
        { word: "portrait", meaning: "초상화" },
        { word: "repudiate", meaning: "거부하다" },
        { word: "correspondingly", meaning: "그에 상응하여" },
        { word: "terminology", meaning: "전문 용어" },
        { word: "remarkable", meaning: "놀라운, 주목할 만한" },
        { word: "simultaneous", meaning: "동시의" },
        { word: "mingle with", meaning: "~와 어울리다" },
        { word: "spontaneous", meaning: "자발적인, 무의식적인, 저절로 움직이는" },
        { word: "fragmentary", meaning: "단편적인" }
    ],
    4: [
        { word: "appreciably", meaning: "상당히" },
        { word: "readily", meaning: "손쉽게, 즉시, 기꺼이" },
        { word: "provoke", meaning: "불러일으키다" },
        { word: "fastidious", meaning: "까다로운" },
        { word: "stimulus", meaning: "자극(제)" },
        { word: "justly", meaning: "공정하게, 정당하게" },
        { word: "advocate", meaning: "지지하다, 지지자" },
        { word: "install", meaning: "설치하다" },
        { word: "prohibitive", meaning: "값이 엄청나게 비싼" },
        { word: "wholesale", meaning: "대규모의, 모조리, 통틀어서" },
        { word: "exposed", meaning: "드러난, 노출된" },
        { word: "renowned", meaning: "유명한" },
        { word: "notion", meaning: "개념, 견해" },
        { word: "forestall", meaning: "미연에 방지하다" },
        { word: "dweller", meaning: "거주자" },
        { word: "tame", meaning: "길들이다" },
        { word: "contraction", meaning: "감소, 축소" },
        { word: "rupture", meaning: "파열되다, 찢어지다, 불화" },
        { word: "homogeneous", meaning: "동종의, 균질의" },
        { word: "dependable", meaning: "신뢰할 수 있는" },
        { word: "ensuing", meaning: "뒤이은, 다음의" },
        { word: "spectrum", meaning: "범위" },
        { word: "practically", meaning: "거의" },
        { word: "intermingled", meaning: "섞인" },
        { word: "alleged", meaning: "추정의" },
        { word: "therefore", meaning: "그 결과" },
        { word: "accurately", meaning: "정확하게" },
        { word: "appeal", meaning: "간청하다" },
        { word: "isolated", meaning: "외딴" },
        { word: "threat", meaning: "위협" },
        { word: "obligate", meaning: "의무를 지우다, 강요하다" },
        { word: "utterly", meaning: "완전히" },
        { word: "chronicle", meaning: "기록, 연대기" },
        { word: "option", meaning: "선택(권)" },
        { word: "persuade", meaning: "설득하다" },
        { word: "momentous", meaning: "중대한" },
        { word: "formidable", meaning: "어마어마한, 경외감을 일으키는" },
        { word: "impermeable", meaning: "침투되지 않는, 통과시키지 않는" },
        { word: "resolve", meaning: "해결하다" },
        { word: "foul", meaning: "더럽히다" },
        { word: "disband", meaning: "해산시키다" },
        { word: "stream", meaning: "흐름" },
        { word: "era", meaning: "시대" },
        { word: "enormous", meaning: "거대한" },
        { word: "succulent", meaning: "즙이 많은" },
        { word: "versatile", meaning: "융통성 있는, 다방면의" },
        { word: "well-to-do", meaning: "부유한" },
        { word: "presuppose", meaning: "(미리) 가정하다" },
        { word: "inherent", meaning: "타고난, 본래의" },
        { word: "track", meaning: "뒤쫓다, (진행 과정 등을) 추적하다" }
    ],
    5: [
        { word: "attributable to", meaning: "~에 기인하는" },
        { word: "stratified", meaning: "층으로 이루어진" },
        { word: "unanticipated", meaning: "예상하지 못한" },
        { word: "incompatible", meaning: "양립할 수 없는" },
        { word: "bulk", meaning: "큰 규모, 대량, 대부분" },
        { word: "outcome", meaning: "결과" },
        { word: "ultimately", meaning: "마침내, 결국" },
        { word: "gratify", meaning: "만족시키다, 기쁘게 하다" },
        { word: "residue", meaning: "잔여물" },
        { word: "trend", meaning: "경향, 추세" },
        { word: "erroneous", meaning: "잘못된" },
        { word: "tenuous", meaning: "빈약한" },
        { word: "fascinating", meaning: "매혹적인" },
        { word: "compelling", meaning: "설득력 있는" },
        { word: "intrinsically", meaning: "본질적으로" },
        { word: "launch", meaning: "시작하다" },
        { word: "eradicate", meaning: "근절하다" },
        { word: "arid", meaning: "메마른" },
        { word: "disputatious", meaning: "논쟁을 좋아하는" },
        { word: "compound", meaning: "(정도를) 더하다, 악화시키다" },
        { word: "eerie", meaning: "기묘한" },
        { word: "unconsolidated", meaning: "굳지 않은" },
        { word: "gather momentum", meaning: "탄력이 붙다" },
        { word: "lodge", meaning: "박히다" },
        { word: "colonize", meaning: "(동∙식물이) 서식하다, 식민지화하다" },
        { word: "embodiment", meaning: "전형, 구체화된 것" },
        { word: "constellation", meaning: "화려한 모임, 무리" },
        { word: "vacate", meaning: "떠나다, 비우다" },
        { word: "circumstance", meaning: "상황" },
        { word: "speculation", meaning: "추측" },
        { word: "merge", meaning: "합치다, 융합하다" },
        { word: "turbulent", meaning: "격동하는" },
        { word: "encounter", meaning: "마주치다, 부닥치다" },
        { word: "predominant", meaning: "주된, 주요한" },
        { word: "seek", meaning: "찾다, 조사하다, 시도하다, 노력하다" },
        { word: "appraisal", meaning: "평가" },
        { word: "cushion", meaning: "보호하다, 충격을 완화하다" },
        { word: "astonishing", meaning: "놀라운, 눈부신" },
        { word: "application", meaning: "응용, 이용" },
        { word: "outstanding", meaning: "뛰어난, 미지불의, 처리되지 않은" },
        { word: "with regard to", meaning: "~에 관하여" },
        { word: "document", meaning: "문서, 기록" },
        { word: "affect", meaning: "영향을 미치다" },
        { word: "proponent", meaning: "지지자" },
        { word: "peculiar", meaning: "특유의, 독특한, 이상한" },
        { word: "inordinate", meaning: "과도한" },
        { word: "enact", meaning: "(법률 등을) 제정하다" },
        { word: "viable", meaning: "생존 가능한" },
        { word: "absolute", meaning: "절대적인, 완전한" },
        { word: "prone to", meaning: "~하기 쉬운" }
    ],
    6: [
        { word: "imaginative", meaning: "창의적인" },
        { word: "sequence", meaning: "연속, 순서" },
        { word: "range", meaning: "범위" },
        { word: "curious", meaning: "호기심이 강한, 이상한, 별난" },
        { word: "consequence", meaning: "결과, 중요성" },
        { word: "vitality", meaning: "활력" },
        { word: "overwhelming", meaning: "압도적인, 굉장한" },
        { word: "equilibrium", meaning: "균형" },
        { word: "hitherto", meaning: "지금까지" },
        { word: "adjacent", meaning: "인접한" },
        { word: "guarantee", meaning: "보장하다" },
        { word: "dramatic", meaning: "극적인, 인상적인" },
        { word: "indifferent", meaning: "무관심한" },
        { word: "prestigious", meaning: "명성이 있는" },
        { word: "disperse", meaning: "흩어지게 하다, 퍼뜨리다" },
        { word: "account", meaning: "(사건 등에 대한) 기술, 보고" },
        { word: "primarily", meaning: "주로, 원래, 처음에" },
        { word: "ample", meaning: "넓은, 광대한, 풍부한" },
        { word: "prosperity", meaning: "번영" },
        { word: "adept", meaning: "능숙한" },
        { word: "flexible", meaning: "유연한, 적응성 있는" },
        { word: "unsuitable", meaning: "적합하지 않은" },
        { word: "replicate", meaning: "모사하다, 복제하다" },
        { word: "detect", meaning: "발견하다, 인지하다" },
        { word: "invariable", meaning: "변함없는" },
        { word: "erupt", meaning: "폭발하다" },
        { word: "inflict", meaning: "(고통 등을) 주다, 가하다" },
        { word: "domain", meaning: "영역" },
        { word: "coincidence", meaning: "우연의 일치" },
        { word: "trace", meaning: "자취, 흔적" },
        { word: "representative", meaning: "나타내는, 전형적인" },
        { word: "incite", meaning: "자극하다" },
        { word: "deteriorate", meaning: "악화되다" },
        { word: "hasty", meaning: "황급한, 서두르는" },
        { word: "portion", meaning: "부분" },
        { word: "unethical", meaning: "비윤리적인" },
        { word: "imposing", meaning: "인상적인" },
        { word: "indeed", meaning: "사실은" },
        { word: "shape", meaning: "(영향을 미쳐) 형성하다" },
        { word: "champion", meaning: "옹호하다" },
        { word: "vehicle", meaning: "수단, 매체" },
        { word: "master", meaning: "습득하다, 제어하다" },
        { word: "surpass", meaning: "능가하다" },
        { word: "surmise", meaning: "추측하다" },
        { word: "plague", meaning: "괴롭히다" },
        { word: "appropriate", meaning: "적절한" },
        { word: "alteration", meaning: "변화, 수정" },
        { word: "detach", meaning: "분리하다" },
        { word: "assimilate", meaning: "(지식 등을) 흡수하다, 이해하다" },
        { word: "contemplate", meaning: "곰곰이 생각하다" }
    ],
    7: [
        { word: "precede", meaning: "~에 앞서다" },
        { word: "flee", meaning: "도망치다, 벗어나다" },
        { word: "chief", meaning: "주요한" },
        { word: "immeasurably", meaning: "대단히" },
        { word: "variety", meaning: "다양성, 종류" },
        { word: "accomplish", meaning: "성취하다" },
        { word: "controversy", meaning: "논쟁" },
        { word: "dominate", meaning: "지배하다, 압도적으로 우세하다" },
        { word: "rudiments", meaning: "기초, 기본" },
        { word: "set", meaning: "고정된, 놓다" },
        { word: "strew", meaning: "흩뿌리다" },
        { word: "assist with", meaning: "~을 돕다" },
        { word: "ratio", meaning: "비율" },
        { word: "preeminent", meaning: "뛰어난" },
        { word: "turmoil", meaning: "소란, 동요" },
        { word: "typically", meaning: "보통" },
        { word: "property", meaning: "특성, 재산" },
        { word: "considerable", meaning: "상당한, 중요한" },
        { word: "extended", meaning: "장기간에 걸친" },
        { word: "relatively", meaning: "비교적으로" },
        { word: "awkward", meaning: "서투른" },
        { word: "reflect", meaning: "나타내다, 숙고하다" },
        { word: "duplicate", meaning: "복제하다, 되풀이하다" },
        { word: "lag", meaning: "지연" },
        { word: "empirical", meaning: "실험상의, 실험에 의한" },
        { word: "interplay", meaning: "상호 작용" },
        { word: "unwieldy", meaning: "(크기∙무게 때문에) 다루기 힘든" },
        { word: "majestic", meaning: "위엄 있는, 웅대한" },
        { word: "legitimately", meaning: "합법적으로, 정당하게" },
        { word: "scrutiny", meaning: "정밀 검사" },
        { word: "article", meaning: "물품" },
        { word: "mortality", meaning: "사망" },
        { word: "constrain", meaning: "강요하다, 억제하다" },
        { word: "severity", meaning: "심함" },
        { word: "rigid", meaning: "엄격한, 굳은, 경직된" },
        { word: "barely", meaning: "거의 ~않게, 간신히" },
        { word: "encapsulate", meaning: "요약하다" },
        { word: "subsequent", meaning: "그 다음의" },
        { word: "striking", meaning: "현저한" },
        { word: "hazard", meaning: "위험" },
        { word: "typical of", meaning: "~을 대표하는" },
        { word: "enable", meaning: "가능하게 하다" },
        { word: "supplementary", meaning: "추가의" },
        { word: "fuel", meaning: "연료를 공급하다, 자극하다" },
        { word: "crude", meaning: "가공하지 않은" },
        { word: "exude", meaning: "(액체∙냄새 등을) 발산하다" },
        { word: "subject", meaning: "피실험자, (싫은 일 등을) 겪게 하다" },
        { word: "manipulation", meaning: "조작" },
        { word: "paramount", meaning: "최고의, 중요한" },
        { word: "dry", meaning: "건조한" }
    ],
    8: [
        { word: "accessible", meaning: "접근할 수 있는, 얻을 수 있는" },
        { word: "extreme", meaning: "극심한, 지나친" },
        { word: "crucial", meaning: "결정적인, 중대한" },
        { word: "voracious", meaning: "만족할 줄 모르는, 탐욕적인" },
        { word: "constituent", meaning: "구성 요소의" },
        { word: "rational", meaning: "합리적인" },
        { word: "enjoy", meaning: "재미를 보다, 즐겁게 경험하다" },
        { word: "extinct", meaning: "멸종된" },
        { word: "demolish", meaning: "파괴하다" },
        { word: "criterion", meaning: "기준" },
        { word: "extract", meaning: "끌어내다, 뽑아내다" },
        { word: "inadvertently", meaning: "무심코" },
        { word: "immensely", meaning: "굉장히" },
        { word: "frankly", meaning: "솔직히" },
        { word: "assess", meaning: "평가하다" },
        { word: "inclination", meaning: "경향, 기호" },
        { word: "friction", meaning: "마찰, 불화" },
        { word: "liberate", meaning: "해방하다" },
        { word: "authentic", meaning: "진짜의" },
        { word: "profuse", meaning: "풍부한" },
        { word: "shoddy", meaning: "질이 떨어지는" },
        { word: "be accompanied by", meaning: "~을 동반하다" },
        { word: "potent", meaning: "(영향 등이) 강력한" },
        { word: "intricate", meaning: "복잡한" },
        { word: "regulate", meaning: "조절하다" },
        { word: "deem", meaning: "생각하다, 여기다" },
        { word: "prevent", meaning: "막다, 방해하다" },
        { word: "ornament", meaning: "장식하다" },
        { word: "materialize", meaning: "나타나다" },
        { word: "consumption", meaning: "소비, 소모" },
        { word: "redundant", meaning: "불필요한, 장황한" },
        { word: "ardent", meaning: "열렬한" },
        { word: "spur", meaning: "자극, 자극하다" },
        { word: "insolent", meaning: "무례한" },
        { word: "determinant", meaning: "결정 요인" },
        { word: "routine", meaning: "틀에 박힌, 평범한" },
        { word: "absorb", meaning: "흡수하다" },
        { word: "peril", meaning: "위험" },
        { word: "demise", meaning: "종말, 몰락" },
        { word: "inflation", meaning: "팽창" },
        { word: "feat", meaning: "위업" },
        { word: "to be sure", meaning: "틀림없이" },
        { word: "as well as", meaning: "~뿐만 아니라" },
        { word: "echo", meaning: "울리다, 반향하다, 흉내 내다" },
        { word: "arduous", meaning: "힘든" },
        { word: "gear", meaning: "맞게 조정하다" },
        { word: "broadly", meaning: "대체로" },
        { word: "resistance", meaning: "반대, 저항" },
        { word: "assemble", meaning: "모으다" },
        { word: "furthermore", meaning: "게다가" }
    ],
    9: [
        { word: "principally", meaning: "주로" },
        { word: "take precedence over", meaning: "~보다 우선하다" },
        { word: "preclude", meaning: "막다, 배제하다" },
        { word: "emerge", meaning: "나타나다" },
        { word: "initiate", meaning: "시작하다" },
        { word: "inducement", meaning: "유인(책), 장려" },
        { word: "idiosyncrasy", meaning: "특징, 이상한 점" },
        { word: "yearn", meaning: "갈망하다" },
        { word: "release", meaning: "석방하다, 방출하다" },
        { word: "rebellion", meaning: "반란" },
        { word: "astute", meaning: "통찰력 있는, 영악한" },
        { word: "snake", meaning: "구불구불 가다" },
        { word: "essentially", meaning: "기본적으로, 본질적으로" },
        { word: "rapidly", meaning: "급속히, 빨리" },
        { word: "widely", meaning: "널리" },
        { word: "phenomenon", meaning: "현상, 사건" },
        { word: "deviation", meaning: "일탈" },
        { word: "acknowledge", meaning: "인정하다" },
        { word: "rough", meaning: "울퉁불퉁한, 거친" },
        { word: "allegiance", meaning: "충성, 헌신" },
        { word: "customary", meaning: "습관적인, 관례적인" },
        { word: "reliable", meaning: "신뢰할 수 있는" },
        { word: "calculatedly", meaning: "계획적으로" },
        { word: "detrimental", meaning: "해로운" },
        { word: "oversee", meaning: "감독하다" },
        { word: "subsistence", meaning: "생존" },
        { word: "allusion", meaning: "(간접적인) 언급, 암시" },
        { word: "keep in check", meaning: "제어하다, 억제하다" },
        { word: "minute", meaning: "아주 작은" },
        { word: "irreversible", meaning: "돌이킬 수 없는" },
        { word: "sophisticated", meaning: "정교한, 고도로 발달한" },
        { word: "notable", meaning: "주목할 만한, 중요한" },
        { word: "assign", meaning: "지정하다" },
        { word: "markedly", meaning: "현저하게" },
        { word: "presumable", meaning: "그럴듯한, 있음직한" },
        { word: "anarchy", meaning: "무질서, 혼란" },
        { word: "derive", meaning: "유래하다, 얻다" },
        { word: "portable", meaning: "휴대용의" },
        { word: "formulate", meaning: "고안하다, 발전시키다, 명확히 말하다" },
        { word: "tremendous", meaning: "엄청난" },
        { word: "sole", meaning: "유일한" },
        { word: "current", meaning: "현재의" },
        { word: "revive", meaning: "회복하다, 소생하다" },
        { word: "equivocal", meaning: "모호한" },
        { word: "renounce", meaning: "포기하다, 버리다" },
        { word: "permit", meaning: "허락하다" },
        { word: "culmination", meaning: "정점, 최고조" },
        { word: "presume", meaning: "~이라고 생각하다, 추정하다" },
        { word: "scarcity", meaning: "부족" },
        { word: "breakthrough", meaning: "큰 발전" }
    ],
    10: [
        { word: "fortify", meaning: "강화하다" },
        { word: "end", meaning: "목적, 목표" },
        { word: "initially", meaning: "처음에" },
        { word: "adhere", meaning: "부착되다, 달라붙다" },
        { word: "devastate", meaning: "완전히 파괴하다" },
        { word: "blur", meaning: "흐리게 하다" },
        { word: "outermost", meaning: "가장 바깥의" },
        { word: "underrate", meaning: "과소평가하다" },
        { word: "thriving", meaning: "번영하는" },
        { word: "virtue", meaning: "미덕, 장점" },
        { word: "unleash", meaning: "(속박을) 풀다" },
        { word: "plentiful", meaning: "풍부한" },
        { word: "bustling", meaning: "붐비는, 떠들썩한" },
        { word: "uniformly", meaning: "균일하게, 한결같이" },
        { word: "critical", meaning: "중요한, 위독한, 위험한" },
        { word: "enigma", meaning: "수수께끼" },
        { word: "luminous", meaning: "빛나는" },
        { word: "modify", meaning: "바꾸다, 조정하다" },
        { word: "make it", meaning: "(제시간에) 도착하다" },
        { word: "as a rule of thumb", meaning: "경험적으로 보아 대개" },
        { word: "scatter", meaning: "흩뿌리다" },
        { word: "scrupulous", meaning: "세심한, 꼼꼼한, 양심적인" },
        { word: "dainty", meaning: "우아한, 섬세한" },
        { word: "optimum", meaning: "최고의" },
        { word: "expandable", meaning: "펼칠 수 있는, 확장할 수 있는" },
        { word: "acquire", meaning: "얻다" },
        { word: "available", meaning: "구할 수 있는" },
        { word: "attest", meaning: "증명하다, 입증하다" },
        { word: "eminently", meaning: "대단히, 현저히" },
        { word: "rapport", meaning: "(친밀한) 관계" },
        { word: "visible", meaning: "눈에 띄는, 명백한" },
        { word: "steadfast", meaning: "변함없는, 단호한" },
        { word: "refinement", meaning: "개선" },
        { word: "cumbersome", meaning: "다루기 힘든" },
        { word: "relay", meaning: "전달하다" },
        { word: "remove", meaning: "제거하다" },
        { word: "boon", meaning: "큰 이익, 혜택" },
        { word: "anomaly", meaning: "이례적인 것, 예외" },
        { word: "obvious", meaning: "분명한" },
        { word: "exceptional", meaning: "이례적인" },
        { word: "source", meaning: "근원, 기원" },
        { word: "question", meaning: "~에 대해 이의를 제기하다" },
        { word: "temporary", meaning: "일시적인" },
        { word: "escalate", meaning: "확대되다, 증대하다" },
        { word: "approximately", meaning: "대략" },
        { word: "distinct", meaning: "다른, 별개의, 뚜렷한" },
        { word: "paradoxical", meaning: "역설적인" },
        { word: "get rid of", meaning: "~을 없애다" },
        { word: "splendid", meaning: "멋진" },
        { word: "attribute", meaning: "특성, ~의 탓(덕)으로 돌리다" }
    ],
    11: [
        { word: "device", meaning: "장치, 기구" },
        { word: "precious", meaning: "귀중한" },
        { word: "arouse", meaning: "자극하다" },
        { word: "swift", meaning: "재빠른" },
        { word: "buffer", meaning: "(충격을) 완화하다, 보호하다" },
        { word: "magnitude", meaning: "규모, 정도" },
        { word: "brew", meaning: "일어나려고 하다" },
        { word: "occupy", meaning: "(주의∙마음을) 끌다" },
        { word: "refine", meaning: "개선하다" },
        { word: "pronounced", meaning: "현저한" },
        { word: "discern", meaning: "파악하다, 알아내다" },
        { word: "transform", meaning: "변형시키다, 바꾸다" },
        { word: "flaw", meaning: "결점" },
        { word: "eccentric", meaning: "별난, 특이한" },
        { word: "conducive to", meaning: "~에 도움이 되는" },
        { word: "bias", meaning: "편견" },
        { word: "celebrated", meaning: "유명한" },
        { word: "virtual", meaning: "거의 ~과 다름없는, 사실상의" },
        { word: "unexplored", meaning: "다루어지지 않은, 논의되지 않은" },
        { word: "splendor", meaning: "장려함, 화려함" },
        { word: "mainly", meaning: "주로" },
        { word: "counterpart", meaning: "(쌍을 이루는) 한 쪽, 동등한 것" },
        { word: "alternative", meaning: "대안이 되는, 다른, 대안" },
        { word: "abnormally", meaning: "이례적으로, 이상하게" },
        { word: "barrier", meaning: "장벽, 장애물" },
        { word: "nevertheless", meaning: "그럼에도 불구하고" },
        { word: "strategy", meaning: "전략, 방법" },
        { word: "administer", meaning: "관리하다, (약 등을) 투여하다, 주다" },
        { word: "temperate", meaning: "(기후 등이) 온화한" },
        { word: "reproduce", meaning: "복제하다, 모사하다, 번식하다" },
        { word: "vertical", meaning: "수직의" },
        { word: "generate", meaning: "만들어 내다" },
        { word: "preoccupied with", meaning: "~에 몰두한" },
        { word: "menace", meaning: "위협하다" },
        { word: "refute", meaning: "논박하다" },
        { word: "innovation", meaning: "혁신, 새로 도입한 것" },
        { word: "tuned to", meaning: "~과 일치된" },
        { word: "chancy", meaning: "위험한" },
        { word: "fragmentation", meaning: "붕괴, 분열" },
        { word: "divergent", meaning: "(의견 등이) 다른, 갈라지는" },
        { word: "allow", meaning: "허락하다" },
        { word: "groundless", meaning: "근거 없는" },
        { word: "persist", meaning: "지속되다" },
        { word: "akin to", meaning: "~과 유사한" },
        { word: "belittle", meaning: "경시하다" },
        { word: "penetrate", meaning: "꿰뚫다" },
        { word: "sue", meaning: "고소하다" },
        { word: "plausible", meaning: "그럴듯한" },
        { word: "commend", meaning: "칭찬하다" },
        { word: "prosper", meaning: "번창하다, 성공하다" }
    ],
    12: [
        { word: "blossom", meaning: "번영하다" },
        { word: "key", meaning: "중요한, (악곡의) 조" },
        { word: "burst", meaning: "터지다" },
        { word: "obtainable", meaning: "얻을 수 있는" },
        { word: "extent", meaning: "범위" },
        { word: "informally", meaning: "비공식적으로" },
        { word: "revolution", meaning: "변혁, 개혁" },
        { word: "duration", meaning: "(지속되는) 기간" },
        { word: "corroborate", meaning: "확증하다" },
        { word: "intimate", meaning: "친밀한" },
        { word: "expedite", meaning: "신속히 처리하다, 촉진시키다" },
        { word: "vibrant", meaning: "활기 넘치는, (색 등이) 선명한" },
        { word: "moreover", meaning: "게다가" },
        { word: "link", meaning: "관계, 유대, 관련짓다" },
        { word: "outlying", meaning: "외진, 중심에서 떨어진" },
        { word: "revolve around", meaning: "~을 중심으로 돌다" },
        { word: "feasible", meaning: "실행 가능한" },
        { word: "groundwork", meaning: "토대, 기초" },
        { word: "define", meaning: "분명히 하다" },
        { word: "irrevocable", meaning: "돌이킬 수 없는" },
        { word: "propulsion", meaning: "추진, 추진력" },
        { word: "posterity", meaning: "후대" },
        { word: "phase", meaning: "시기, 단계" },
        { word: "massive", meaning: "대규모의, 거대한" },
        { word: "accumulation", meaning: "축적" },
        { word: "scenario", meaning: "(사건의) 시나리오" },
        { word: "randomness", meaning: "무작위성" },
        { word: "aggravate", meaning: "악화시키다" },
        { word: "trivial", meaning: "사소한" },
        { word: "execute", meaning: "수행하다, (미술품 등을) 제작하다" },
        { word: "burgeoning", meaning: "급증하는" },
        { word: "inaugurate", meaning: "개시하다, 시작하다" },
        { word: "urbane", meaning: "세련된" },
        { word: "diversion", meaning: "주의 전환물" },
        { word: "tendency", meaning: "경향" },
        { word: "ingenious", meaning: "기발한, 독창적인" },
        { word: "eventually", meaning: "결국" },
        { word: "superficial", meaning: "표면적인" },
        { word: "constitute", meaning: "구성하다" },
        { word: "envision", meaning: "마음속에 그리다, 상상하다" },
        { word: "persistent", meaning: "지속되는" },
        { word: "frightful", meaning: "무서운" },
        { word: "further", meaning: "추가적인" },
        { word: "concentrate on", meaning: "~에 집중하다" },
        { word: "terrestrial", meaning: "속세의" },
        { word: "utilitarian", meaning: "실용적인" },
        { word: "originate from", meaning: "~에서 비롯되다" },
        { word: "resolute", meaning: "확고한" },
        { word: "adorn", meaning: "꾸미다" },
        { word: "artifact", meaning: "인공 유물" }
    ],
    13: [
        { word: "occasionally", meaning: "가끔" },
        { word: "besides", meaning: "게다가, ~ 외에" },
        { word: "precise", meaning: "정확한" },
        { word: "merely", meaning: "단지" },
        { word: "retrieve", meaning: "되찾다" },
        { word: "emit", meaning: "내뿜다, 방출하다" },
        { word: "sparse", meaning: "드문드문한, 부족한" },
        { word: "somewhat", meaning: "어느 정도" },
        { word: "collaborate", meaning: "협력하다" },
        { word: "stunning", meaning: "놀랄 만큼 멋진" },
        { word: "deliberation", meaning: "토의" },
        { word: "model", meaning: "견본" },
        { word: "favor", meaning: "더 좋아하다" },
        { word: "damaging", meaning: "해로운" },
        { word: "dissemination", meaning: "보급, 유포" },
        { word: "incentive", meaning: "동기, 자극" },
        { word: "preposterous", meaning: "터무니없는" },
        { word: "enhance", meaning: "향상시키다" },
        { word: "perspective", meaning: "관점" },
        { word: "rate", meaning: "평가하다" },
        { word: "compress", meaning: "압축하다" },
        { word: "owing to", meaning: "~ 때문에" },
        { word: "abandoned", meaning: "버려진" },
        { word: "compulsorily", meaning: "의무적으로" },
        { word: "habit", meaning: "습관" },
        { word: "realize", meaning: "깨닫다, 이해하다, 달성하다, 실현하다" },
        { word: "share", meaning: "몫" },
        { word: "decimate", meaning: "(많은 사람을) 죽이다" },
        { word: "stipulate", meaning: "(조건으로서) 요구하다" },
        { word: "full-fledged", meaning: "완전히 발달한" },
        { word: "with respect to", meaning: "~에 관하여" },
        { word: "shortly", meaning: "곧" },
        { word: "overriding", meaning: "가장 중요한" },
        { word: "anonymous", meaning: "익명의, 신원 불명의" },
        { word: "circuitous", meaning: "우회하는" },
        { word: "evident", meaning: "분명한" },
        { word: "inconceivable", meaning: "상상도 할 수 없는" },
        { word: "breeding", meaning: "번식" },
        { word: "heighten", meaning: "고조시키다" },
        { word: "clever", meaning: "영리한" },
        { word: "consistently", meaning: "일관되게" },
        { word: "laborious", meaning: "인내를 요하는, 힘든" },
        { word: "fundamental", meaning: "근본적인, 기본적인" },
        { word: "marked", meaning: "두드러진, 현저한" },
        { word: "shift", meaning: "옮기다, 바꾸다" },
        { word: "candidly", meaning: "솔직히" },
        { word: "continuous", meaning: "계속되는" },
        { word: "tantalizing", meaning: "흥미를 돋우는, 감질나는" },
        { word: "hypothetical", meaning: "가상의, 가정의" },
        { word: "transmit", meaning: "전하다" }
    ],
    14: [
        { word: "potential", meaning: "잠재적인, 가능성" },
        { word: "pragmatic", meaning: "실용적인" },
        { word: "obligation", meaning: "의무, 책임" },
        { word: "exclusively", meaning: "오로지, 전적으로" },
        { word: "anchor", meaning: "고정시키다" },
        { word: "throughout", meaning: "~ 동안, 내내" },
        { word: "given that", meaning: "~을 고려하면" },
        { word: "peak", meaning: "정점, 절정" },
        { word: "profoundly", meaning: "깊이, 대단히" },
        { word: "coinage", meaning: "신조어" },
        { word: "hollow", meaning: "속이 빈" },
        { word: "now and then", meaning: "가끔" },
        { word: "cargo", meaning: "화물, 짐" },
        { word: "unthinkable", meaning: "상상도 할 수 없는" },
        { word: "inconclusive", meaning: "결정적이지 않은" },
        { word: "improbable", meaning: "있음직하지 않은" },
        { word: "appreciable", meaning: "주목할 만한" },
        { word: "surge", meaning: "급증하다" },
        { word: "continual", meaning: "끊임없는" },
        { word: "lethal", meaning: "치명적인" },
        { word: "methodically", meaning: "체계적으로" },
        { word: "accurate", meaning: "정확한" },
        { word: "discrete", meaning: "별개의" },
        { word: "recurring", meaning: "되풀이되는" },
        { word: "mobilize", meaning: "동원하다" },
        { word: "undisputed", meaning: "모두가 인정하는" },
        { word: "deflect", meaning: "방향을 바꾸다" },
        { word: "manage to", meaning: "간신히 ~하다" },
        { word: "prevail", meaning: "널리 퍼지다, 만연하다, 이기다" },
        { word: "withstand", meaning: "견디다" },
        { word: "clue", meaning: "단서, 증거" },
        { word: "coupled with", meaning: "~과 결합된" },
        { word: "span", meaning: "기간, 걸치다" },
        { word: "pitfall", meaning: "위험, 어려움" },
        { word: "scorn", meaning: "비웃다, 경멸하다" },
        { word: "severe", meaning: "엄한, 가혹한" },
        { word: "deliberately", meaning: "일부러" },
        { word: "spearhead", meaning: "앞장서다" },
        { word: "cornerstone", meaning: "토대, 기초" },
        { word: "relic", meaning: "유물, 나머지" },
        { word: "shield", meaning: "보호하다" },
        { word: "meager", meaning: "불충분한" },
        { word: "solitary", meaning: "외딴, 외로운" },
        { word: "unintentionally", meaning: "의도치 않게" },
        { word: "reconcile", meaning: "화해시키다" },
        { word: "hasten", meaning: "재촉하다" },
        { word: "exploitation", meaning: "(부당한) 이용, 착취" },
        { word: "modest", meaning: "그리 크지(많지) 않은, 수수한" },
        { word: "huge", meaning: "거대한" },
        { word: "foremost", meaning: "으뜸가는" }
    ],
    15: [
        { word: "congeal", meaning: "굳다, 응고하다" },
        { word: "relevant", meaning: "관련된, 적절한" },
        { word: "prominently", meaning: "눈에 띄게" },
        { word: "reasonable", meaning: "합리적인, (가격이) 적당한" },
        { word: "cautious", meaning: "신중한, 조심성 있는" },
        { word: "characteristic", meaning: "특유의, 특징, 특성" },
        { word: "identical", meaning: "동일한" },
        { word: "tactic", meaning: "전략" },
        { word: "embody", meaning: "구체적으로 나타내다, 포함하다" },
        { word: "bountifully", meaning: "풍부하게" },
        { word: "suppress", meaning: "억제하다, 참다, 진압하다" },
        { word: "substantial", meaning: "상당한" },
        { word: "variation", meaning: "변동, 차이" },
        { word: "deplete", meaning: "다 써버리다, 대폭 감소시키다" },
        { word: "albeit", meaning: "비록 ~이지만" },
        { word: "intact", meaning: "손상되지 않은" },
        { word: "evade", meaning: "피하다" },
        { word: "apparently", meaning: "외관상으로는" },
        { word: "oblige", meaning: "강요하다" },
        { word: "remarkably", meaning: "신기하게도" },
        { word: "flattery", meaning: "아첨" },
        { word: "dam", meaning: "(둑으로) 막다" },
        { word: "spot", meaning: "발견하다" },
        { word: "attainment", meaning: "성취" },
        { word: "prime", meaning: "최고의, 주요한" },
        { word: "grasp", meaning: "이해하다" },
        { word: "not in consensus with", meaning: "(의견이) ~와 일치하지 않는" },
        { word: "sustained", meaning: "지속적인" },
        { word: "immerse", meaning: "(물에) 잠그다, 담그다" },
        { word: "realm", meaning: "영역, 범위" },
        { word: "complex", meaning: "복잡한, 복합 건물, 복합체" },
        { word: "incidentally", meaning: "덧붙여 말하자면, 그런데" },
        { word: "radical", meaning: "근본적인, 극단적인, 과격한" },
        { word: "periphery", meaning: "주변" },
        { word: "inception", meaning: "시작, 개시" },
        { word: "verify", meaning: "입증하다" },
        { word: "ambitious", meaning: "야심 있는" },
        { word: "due to", meaning: "~로 인한, ~에 기인하는" },
        { word: "dimension", meaning: "크기, 규모" },
        { word: "disputable", meaning: "논란의 여지가 있는" },
        { word: "amplify", meaning: "확대하다, 증대하다" },
        { word: "precipitate", meaning: "재촉하다, 촉진하다" },
        { word: "tempted to", meaning: "~하고 싶어지다" },
        { word: "far-reaching", meaning: "광범위한" },
        { word: "questionable", meaning: "의심스러운" },
        { word: "interlock", meaning: "서로 맞물리다" },
        { word: "classify", meaning: "분류하다" },
        { word: "ice sheet", meaning: "대륙 빙하" },
        { word: "against", meaning: "~에 붙여, ~에 가까이" },
        { word: "accordingly", meaning: "그에 따라서" }
    ],
    16: [
        { word: "collision", meaning: "충돌" },
        { word: "paradoxically", meaning: "역설적으로" },
        { word: "impervious", meaning: "통과할 수 없는" },
        { word: "fabricate", meaning: "만들어 내다" },
        { word: "inspect", meaning: "검사하다" },
        { word: "rudimentary", meaning: "기본적인, 기초의, 미발달의" },
        { word: "archetypal", meaning: "전형적인" },
        { word: "standpoint", meaning: "관점, 견해" },
        { word: "pace", meaning: "속도" },
        { word: "abandon", meaning: "버리다, 포기하다" },
        { word: "subsequently", meaning: "그 후에" },
        { word: "hence", meaning: "따라서, 그러므로" },
        { word: "maintain", meaning: "유지하다, 주장하다" },
        { word: "transitory", meaning: "일시적인" },
        { word: "abundant", meaning: "풍부한" },
        { word: "catastrophic", meaning: "비극적인, 파멸의" },
        { word: "significant", meaning: "상당한, 중요한" },
        { word: "aridity", meaning: "건조함" },
        { word: "drive", meaning: "몰아가다, 추진력, 진취성, (조직적인) 운동" },
        { word: "differential", meaning: "차별적인" },
        { word: "pristine", meaning: "자연 그대로의, 오염되지 않은" },
        { word: "outbreak", meaning: "급격한 증가, (질병 등의) 창궐" },
        { word: "jointly", meaning: "함께, 공동으로" },
        { word: "supersede", meaning: "대신하다" },
        { word: "steadily", meaning: "끊임없이" },
        { word: "explicit", meaning: "분명한" },
        { word: "quantify", meaning: "양을 재다, 측정하다" },
        { word: "spawn", meaning: "야기하다" },
        { word: "meet", meaning: "(문제∙위기에) 대처하다" },
        { word: "augment", meaning: "증가시키다" },
        { word: "utilize", meaning: "이용하다" },
        { word: "moderate", meaning: "누그러지다, 온건한, 온화한" },
        { word: "anxiety", meaning: "걱정, 불안" },
        { word: "coarse", meaning: "거친" },
        { word: "allude to", meaning: "~을 넌지시 언급하다" },
        { word: "fuse", meaning: "녹다, 녹이다, 융합하다" },
        { word: "inviolable", meaning: "(법 등이) 어길 수 없는, 신성한" },
        { word: "purposely", meaning: "고의로" },
        { word: "prowess", meaning: "뛰어난 솜씨" },
        { word: "devour", meaning: "게걸스럽게 먹다" },
        { word: "assertive", meaning: "자기주장이 강한, 독단적인" },
        { word: "cue", meaning: "신호" },
        { word: "prevailing", meaning: "(의견 등이) 지배적인" },
        { word: "trespass", meaning: "불법 침입하다" },
        { word: "lax", meaning: "태만한" },
        { word: "amiss", meaning: "잘못된" },
        { word: "figure out", meaning: "알아내다" },
        { word: "implant", meaning: "심다, 끼워 넣다" },
        { word: "stagnant", meaning: "활발하지 않은" },
        { word: "aggregation", meaning: "집단" }
    ],
    17: [
        { word: "in earnest", meaning: "진지하게" },
        { word: "transparent", meaning: "투명한, 명백한" },
        { word: "overlook", meaning: "간과하다" },
        { word: "intensify", meaning: "강화하다" },
        { word: "incorporate", meaning: "통합하다" },
        { word: "justify", meaning: "옹호하다, (정당성을) 증명하다" },
        { word: "critically", meaning: "결정적으로" },
        { word: "secure", meaning: "확보하다, 안전한" },
        { word: "hamper", meaning: "방해하다" },
        { word: "terrain", meaning: "지역, 지형" },
        { word: "subsist", meaning: "생존하다" },
        { word: "dismantle", meaning: "분해하다" },
        { word: "pioneer", meaning: "선구자, 개척하다" },
        { word: "dispose of", meaning: "~을 처리하다" },
        { word: "intangible", meaning: "무형의" },
        { word: "inflate", meaning: "부풀다, 부풀리다" },
        { word: "imprecise", meaning: "부정확한" },
        { word: "orchestrate", meaning: "조직하다" },
        { word: "exempt", meaning: "면제된" },
        { word: "tolerate", meaning: "용인하다, 허용하다" },
        { word: "heritage", meaning: "유산, 전통" },
        { word: "undoubtedly", meaning: "확실히" },
        { word: "threshold", meaning: "한계점, 기준점" },
        { word: "lavish", meaning: "풍부한, 호화로운" },
        { word: "dynamic", meaning: "역동적인, 원동력, 힘" },
        { word: "commence", meaning: "시작하다" },
        { word: "ultimate", meaning: "최종의, 궁극적인, 근본적인" },
        { word: "meticulous", meaning: "꼼꼼한" },
        { word: "brittle", meaning: "부러지기 쉬운, 깨지기 쉬운" },
        { word: "chaotic", meaning: "무질서한" },
        { word: "roughly", meaning: "대략" },
        { word: "persuasively", meaning: "설득력 있게" },
        { word: "miraculous", meaning: "기적적인, 놀라운" },
        { word: "prominence", meaning: "중요성" },
        { word: "improvised", meaning: "즉흥의" },
        { word: "rather", meaning: "오히려, 좀, 약간" },
        { word: "converge", meaning: "모이다" },
        { word: "orientation", meaning: "성향, 경향, 오리엔테이션" },
        { word: "impetus", meaning: "자극" },
        { word: "as a whole", meaning: "전체적으로" },
        { word: "prolonged", meaning: "오래 계속되는" },
        { word: "state", meaning: "명시하다" },
        { word: "stem from", meaning: "~에서 유래하다" },
        { word: "agile", meaning: "민첩한" },
        { word: "standstill", meaning: "정지, 멈춤" },
        { word: "commemorate", meaning: "기념하다" },
        { word: "henceforth", meaning: "지금부터는" },
        { word: "prevalent", meaning: "일반적인, 널리 퍼진" },
        { word: "dormant", meaning: "활동하지 않는, 휴면 중인" },
        { word: "archive", meaning: "공식 기록" }
    ],
    18: [
        { word: "ornamental", meaning: "장식용의" },
        { word: "rapid", meaning: "빠른" },
        { word: "comprehensible", meaning: "이해할 수 있는" },
        { word: "stress", meaning: "강조하다, 중점, 강조" },
        { word: "decompose", meaning: "부패하다" },
        { word: "copious", meaning: "풍부한" },
        { word: "tangible", meaning: "유형의, 실재하는" },
        { word: "contentious", meaning: "논쟁을 불러일으키는" },
        { word: "efface", meaning: "지우다, 없애다" },
        { word: "regime", meaning: "정권, 체제" },
        { word: "notably", meaning: "특히" },
        { word: "initiative", meaning: "진취성" },
        { word: "lateral", meaning: "측면의" },
        { word: "tantalize", meaning: "애타게 하다" },
        { word: "buildup", meaning: "축적" },
        { word: "likewise", meaning: "마찬가지로, 똑같이, 또한" },
        { word: "moral", meaning: "교훈" },
        { word: "consume", meaning: "소비하다, 소멸시키다, 먹다" },
        { word: "routinely", meaning: "일상적으로" },
        { word: "spectacular", meaning: "장관인, 눈부신" },
        { word: "adapt", meaning: "적응하다" },
        { word: "inclement", meaning: "(날씨가) 혹독한" },
        { word: "authoritative", meaning: "권위 있는, 믿을 만한" },
        { word: "string", meaning: "일련" },
        { word: "approach", meaning: "접근하다, 접근법" },
        { word: "phenomenal", meaning: "경이적인" },
        { word: "compatible", meaning: "일치하는, 양립할 수 있는" },
        { word: "competent", meaning: "유능한" },
        { word: "rely upon", meaning: "~에 의존하다" },
        { word: "saturate", meaning: "흠뻑 적시다" },
        { word: "unambiguous", meaning: "분명한" },
        { word: "manageable", meaning: "관리하기 쉬운" },
        { word: "noteworthy", meaning: "주목할 만한" },
        { word: "provided that", meaning: "만약 ~이라면" },
        { word: "proliferation", meaning: "급증" },
        { word: "disparity", meaning: "차이, 불균형" },
        { word: "respective", meaning: "각각의, 개별적인" },
        { word: "promote", meaning: "촉진하다" },
        { word: "negligible", meaning: "사소한" },
        { word: "implication", meaning: "결과" },
        { word: "constitution", meaning: "구성, 구조" },
        { word: "rigor", meaning: "엄격함, 고초, 어려움" },
        { word: "allied", meaning: "관련된" },
        { word: "extracted from", meaning: "~에서 뽑아낸" },
        { word: "overly", meaning: "지나치게" },
        { word: "peculiarity", meaning: "(기이한) 특징, 특성" },
        { word: "bold", meaning: "용감한" },
        { word: "inhibit", meaning: "금지하다" },
        { word: "overall", meaning: "전반적인" },
        { word: "acclaim", meaning: "격찬하다" }
    ],
    19: [
        { word: "forage", meaning: "(식량 등을) 찾아다니다, 사료, 먹이" },
        { word: "decisive", meaning: "결정적인, 명백한" },
        { word: "appreciate", meaning: "인식하다" },
        { word: "elevate", meaning: "들어 올리다" },
        { word: "swell", meaning: "팽창하다, 팽창시키다" },
        { word: "mold", meaning: "형성하다, 만들다" },
        { word: "erect", meaning: "세우다, 건설하다" },
        { word: "frigid", meaning: "몹시 추운" },
        { word: "by and large", meaning: "대체로" },
        { word: "primordial", meaning: "최초의" },
        { word: "bizarre", meaning: "이상한, 기괴한" },
        { word: "refrain from", meaning: "~을 삼가다" },
        { word: "complaint", meaning: "불만, 항의" },
        { word: "accommodate", meaning: "수용하다, 적응하다, 맞추다" },
        { word: "glimpse into", meaning: "~을 흘끗 봄" },
        { word: "accomplished", meaning: "숙련된" },
        { word: "objective", meaning: "목적, 목표, 편견 없는" },
        { word: "annual", meaning: "연간의" },
        { word: "integral", meaning: "필수적인, 완전한, 빠진 것이 없는" },
        { word: "complement", meaning: "금상첨화격 요소, 보완물" },
        { word: "obscure", meaning: "흐릿한, 불분명한" },
        { word: "underscore", meaning: "강조하다" },
        { word: "infinite", meaning: "무한한" },
        { word: "impact", meaning: "영향" },
        { word: "tend", meaning: "돌보다" },
        { word: "uniform", meaning: "일정한, 한결같은" },
        { word: "thus", meaning: "따라서" },
        { word: "vigor", meaning: "활력, 힘" },
        { word: "expansion", meaning: "팽창, 확장" },
        { word: "engender", meaning: "야기하다" },
        { word: "precisely", meaning: "정확하게" },
        { word: "minutely", meaning: "자세하게" },
        { word: "luxuriant", meaning: "무성한" },
        { word: "wary", meaning: "경계하는" },
        { word: "conceal", meaning: "숨기다, 감추다" },
        { word: "inspire", meaning: "영감을 주다" },
        { word: "subordinate", meaning: "종속적인" },
        { word: "thrive", meaning: "번성하다" },
        { word: "deficient", meaning: "부족한" },
        { word: "cluster", meaning: "(떼를 지어) 모이다, 모으다" },
        { word: "deviate", meaning: "벗어나다" },
        { word: "autonomy", meaning: "자치(권)" },
        { word: "altogether", meaning: "완전히" },
        { word: "adverse", meaning: "부정적인" },
        { word: "propagation", meaning: "보급, 전파" },
        { word: "handle", meaning: "처리하다" },
        { word: "revise", meaning: "수정하다, 변경하다" },
        { word: "rebound", meaning: "다시 일어서다, 회복되다" },
        { word: "indiscriminately", meaning: "무차별로, 가리지 않고" },
        { word: "superb", meaning: "훌륭한" }
    ],
    20: [
        { word: "conform", meaning: "따르다" },
        { word: "traumatic", meaning: "정신적 충격이 큰" },
        { word: "pertinent", meaning: "관련된" },
        { word: "resume", meaning: "다시 시작하다" },
        { word: "dual", meaning: "이중의" },
        { word: "invaluable", meaning: "매우 귀중한" },
        { word: "shatter", meaning: "산산이 부수다" },
        { word: "mimic", meaning: "흉내 내다, 모방하다" },
        { word: "prestige", meaning: "명성, 위신" },
        { word: "suppose", meaning: "추측하다" },
        { word: "composite", meaning: "합성물" },
        { word: "radically", meaning: "철저하게, 근본적으로" },
        { word: "harness", meaning: "(자연의 힘 등을) 이용하다" },
        { word: "cling to", meaning: "~에 달라붙다" },
        { word: "mastery", meaning: "통제력, 지배, 전문적 지식" },
        { word: "primitive", meaning: "초기의, 발달되지 않은" },
        { word: "size up", meaning: "평가하다" },
        { word: "stationary", meaning: "움직이지 않는" },
        { word: "successive", meaning: "연속적인" },
        { word: "initial", meaning: "최초의" },
        { word: "verging on", meaning: "~에 가까운, 거의 ~인" },
        { word: "excrete", meaning: "배설하다, 방출하다" },
        { word: "coating", meaning: "코팅, 칠, 입힌 것" },
        { word: "barren", meaning: "척박한, 불모의" },
        { word: "essential", meaning: "근본적인, 필수적인" },
        { word: "exhibit", meaning: "보이다, 나타내다" },
        { word: "point out", meaning: "지적하다, 언급하다" },
        { word: "harsh", meaning: "가혹한" },
        { word: "perpetually", meaning: "끊임없이" },
        { word: "sought-after", meaning: "수요가 많은, 인기 있는" },
        { word: "expand", meaning: "확장시키다, 확장하다" },
        { word: "confirm", meaning: "확인하다" },
        { word: "rekindle", meaning: "다시 불붙이다, 되살아나게 하다" },
        { word: "gradually", meaning: "서서히" },
        { word: "illuminate", meaning: "밝게 하다, 명확하게 하다" },
        { word: "deposit", meaning: "놓다, 두다" },
        { word: "allure", meaning: "매혹하다" },
        { word: "adherent", meaning: "지지자" },
        { word: "devastation", meaning: "파괴" },
        { word: "give rise to", meaning: "~을 초래하다" },
        { word: "interrupt", meaning: "중단시키다" },
        { word: "contemptuous", meaning: "업신여기는" },
        { word: "evacuate", meaning: "대피하다, 비우고 떠나다" },
        { word: "engage", meaning: "참여시키다, (대화 등에) 끌어들이다, (방∙좌석 등을) 예약하다, 고용하다" },
        { word: "accelerate", meaning: "속도를 높이다" },
        { word: "consent", meaning: "동의하다" },
        { word: "combine", meaning: "결합시키다" },
        { word: "dispersal", meaning: "확산, 분산" },
        { word: "affluent", meaning: "풍부한, 부유한" },
        { word: "contiguous", meaning: "인접한" }
    ],
    21: [
        { word: "discount", meaning: "무시하다" },
        { word: "constant", meaning: "변함없는, 일정한" },
        { word: "spell", meaning: "한동안" },
        { word: "contain", meaning: "포함하다" },
        { word: "or so", meaning: "~정도" },
        { word: "unwilling", meaning: "마지못해 하는, 꺼리는" },
        { word: "prompt", meaning: "유발하다, 자극하다" },
        { word: "profound", meaning: "엄청난, 깊은, 심오한, 폭넓은" },
        { word: "random", meaning: "무작위의, 우연한" },
        { word: "proposal", meaning: "제안" },
        { word: "sophistication", meaning: "(고도의) 지식" },
        { word: "ambivalent", meaning: "상반되는 감정을 가진" },
        { word: "fragment", meaning: "조각, 부분, 산산이 부수다, 부서지다" },
        { word: "intrusive", meaning: "개입하는, 참견하는" },
        { word: "mundane", meaning: "일상적인, 평범한" },
        { word: "contradicting", meaning: "서로 대립하는" },
        { word: "for all", meaning: "~에도 불구하고" },
        { word: "erode", meaning: "침식시키다, 침식되다" },
        { word: "appreciation", meaning: "이해" },
        { word: "ingenuity", meaning: "창의력, 교묘함" },
        { word: "flawed", meaning: "결함이 있는" },
        { word: "ancient", meaning: "고대의" },
        { word: "apex", meaning: "정점" },
        { word: "matter", meaning: "물질, 사안" },
        { word: "flag", meaning: "시들다, 줄다" },
        { word: "persistence", meaning: "지속" },
        { word: "dejected", meaning: "낙담한" },
        { word: "destitute of", meaning: "~이 없는" },
        { word: "term", meaning: "칭하다" },
        { word: "mutation", meaning: "돌연변이 과정, 변화, 변형" },
        { word: "infer", meaning: "추론하다" },
        { word: "criticize", meaning: "비난하다" },
        { word: "dense", meaning: "밀집한, 빽빽한" },
        { word: "dissipate", meaning: "(구름·안개 등을) 흩뜨리다, 흩어지다" },
        { word: "facet", meaning: "측면" },
        { word: "considerably", meaning: "상당히" },
        { word: "tension", meaning: "긴장, 압박" },
        { word: "core", meaning: "핵심" },
        { word: "juncture", meaning: "연결, 접합" },
        { word: "distinction", meaning: "차이" },
        { word: "flourish", meaning: "번창하다" },
        { word: "mutilate", meaning: "못쓰게 만들다" },
        { word: "sporadic", meaning: "때때로 일어나는" },
        { word: "inherently", meaning: "본질적으로" },
        { word: "though", meaning: "그렇지만, ~이지만" },
        { word: "uniquely", meaning: "독특하게" },
        { word: "thrill", meaning: "흥분, 전율" },
        { word: "reminisce", meaning: "회상하다" },
        { word: "regrettably", meaning: "유감스럽게도" },
        { word: "rigidly", meaning: "엄격하게" }
    ],
    22: [
        { word: "flexibility", meaning: "융통성, 적응성" },
        { word: "circumvent", meaning: "우회하다" },
        { word: "aggregate", meaning: "총계의, 집합적인, 모이다, 모으다" },
        { word: "epitomize", meaning: "~의 전형이 되다, 요약하다" },
        { word: "compel", meaning: "강요하다" },
        { word: "simultaneously", meaning: "동시에" },
        { word: "interpret", meaning: "해석하다, 이해하다" },
        { word: "static", meaning: "변화가 없는, 고정된" },
        { word: "eager to", meaning: "~을 하고 싶어하는" },
        { word: "skeptical", meaning: "의심 많은" },
        { word: "exceptionally", meaning: "유난히" },
        { word: "lucid", meaning: "명료한" },
        { word: "turbulence", meaning: "소란, 동요" },
        { word: "disclose", meaning: "(비밀 등을) 밝히다, 폭로하다" },
        { word: "accompany", meaning: "동반하다" },
        { word: "limited", meaning: "제한된, 한정된" },
        { word: "forum", meaning: "공공 광장" },
        { word: "thwart", meaning: "좌절시키다" },
        { word: "challenge", meaning: "문제, 난제, 이의를 제기하다" },
        { word: "constantly", meaning: "끊임없이" },
        { word: "vanish", meaning: "사라지다" },
        { word: "endeavor", meaning: "노력하다, 시도하다" },
        { word: "opposing", meaning: "상반되는, 모순되는" },
        { word: "similar", meaning: "비슷한" },
        { word: "scores", meaning: "다수" },
        { word: "obtain", meaning: "얻다, 획득하다" },
        { word: "potentially", meaning: "어쩌면" },
        { word: "hazardous", meaning: "위험한" },
        { word: "location", meaning: "장소, 지역" },
        { word: "excessive", meaning: "지나친" },
        { word: "optimal", meaning: "최적의, 최선의" },
        { word: "retain", meaning: "보유하다, 유지하다" },
        { word: "entitled to", meaning: "~할 권리가 있는" },
        { word: "unpromising", meaning: "가망이 없는" },
        { word: "sloping", meaning: "경사진" },
        { word: "staggering", meaning: "충격적인" },
        { word: "invade", meaning: "침입하다" },
        { word: "eject", meaning: "쫓아내다" },
        { word: "heed", meaning: "주의" },
        { word: "surveillance", meaning: "감시" },
        { word: "systematically", meaning: "체계적으로" },
        { word: "stimulate", meaning: "자극하다, 활성화시키다" },
        { word: "delineate", meaning: "(윤곽 등을) 그리다" },
        { word: "synthesis", meaning: "통합" },
        { word: "back up", meaning: "지지하다, 지원하다" },
        { word: "hint", meaning: "암시, 단서" },
        { word: "intensity", meaning: "강도, 세기" },
        { word: "practical", meaning: "실용적인, 효과적인" },
        { word: "essence", meaning: "본질" },
        { word: "abolish", meaning: "(법률∙제도 등을) 폐지하다" }
    ],
    23: [
        { word: "engulf", meaning: "(불∙파도 등이) 삼켜 버리다" },
        { word: "requisite", meaning: "필수품, 필요조건, 필수의" },
        { word: "furnish", meaning: "제공하다" },
        { word: "accidental", meaning: "우연한" },
        { word: "confine", meaning: "경계, 범위, 가두다, 제한하다" },
        { word: "determine", meaning: "결정하다, 측정하다" },
        { word: "illusory", meaning: "착각을 일으키는" },
        { word: "transplant", meaning: "이동시키다" },
        { word: "invent", meaning: "발명하다" },
        { word: "attain", meaning: "(목적지∙고령 등에) 도달하다, 성취하다, 얻다" },
        { word: "durable", meaning: "오래가는" },
        { word: "vivid", meaning: "선명한, 생생한" },
        { word: "alter", meaning: "변경하다, 바꾸다" },
        { word: "dictate", meaning: "(권위를 갖고) 지시하다, 좌우하다, 결정하다" },
        { word: "proficient", meaning: "능숙한" },
        { word: "mandate", meaning: "명령, 지시" },
        { word: "collectively", meaning: "공동으로" },
        { word: "truism", meaning: "뻔한 말, 자명한 이치" },
        { word: "prosperous", meaning: "번영하는, 부유한" },
        { word: "found wanting", meaning: "부족하다고 여겨지는" },
        { word: "forerunner", meaning: "선조, 선구자" },
        { word: "eventual", meaning: "최종적인" },
        { word: "pledge", meaning: "약속, 맹세" },
        { word: "grossly", meaning: "지나치게" },
        { word: "induce", meaning: "야기하다, 유발하다, 설득하다" },
        { word: "uneasy", meaning: "불안한, 불안정한" },
        { word: "be inclined to", meaning: "~하는 경향이 있다" },
        { word: "erratic", meaning: "불규칙한" },
        { word: "magnificent", meaning: "굉장히 멋진" },
        { word: "crush", meaning: "(희망·사기를) 꺾다" },
        { word: "camouflage", meaning: "위장하다, 감추다" },
        { word: "secluded", meaning: "외딴" },
        { word: "contend", meaning: "주장하다" },
        { word: "expose", meaning: "드러내다, 노출시키다" },
        { word: "classic", meaning: "전형적인, 대표적인" },
        { word: "amply", meaning: "풍부하게" },
        { word: "disrupt", meaning: "방해하다" },
        { word: "implement", meaning: "도구, 기구" },
        { word: "approximation", meaning: "근접성, 가까움" },
        { word: "configuration", meaning: "배치, (배치) 형태" },
        { word: "artificial", meaning: "인조의, 인공의" },
        { word: "desolate", meaning: "황량한" },
        { word: "immediate", meaning: "즉각적인, 인접한" },
        { word: "wield", meaning: "(권력·무기 등을) 휘두르다, 행사하다" },
        { word: "haul", meaning: "끌고 가다, 끌다" },
        { word: "excavate", meaning: "파내다, 발굴하다" },
        { word: "disgust", meaning: "혐오감, 불쾌감" },
        { word: "inherent in", meaning: "~에 내재된" },
        { word: "partake of", meaning: "함께 먹다, 함께 하다" },
        { word: "manner", meaning: "방법, 방식" }
    ],
    24: [
        { word: "convey", meaning: "전달하다" },
        { word: "assert", meaning: "주장하다" },
        { word: "concern", meaning: "걱정시키다, 관심(사)" },
        { word: "sustain", meaning: "떠받치다, 지탱하다, 지속하다, 유지하다" },
        { word: "prized", meaning: "뛰어난, 소중한" },
        { word: "to a large extent", meaning: "대체로" },
        { word: "impulse", meaning: "자극(제)" },
        { word: "gain", meaning: "증가" },
        { word: "subsequence", meaning: "연속, 이어서 일어나는 것" },
        { word: "firmly", meaning: "단단히" },
        { word: "comparable", meaning: "비슷한, 동등한" },
        { word: "cognitive", meaning: "인지(력)의, 정신적 작용의" },
        { word: "presumably", meaning: "아마" },
        { word: "notwithstanding", meaning: "~에도 불구하고" },
        { word: "unexpectedly", meaning: "뜻밖에" },
        { word: "cramped", meaning: "비좁은, 제한된" },
        { word: "tempting", meaning: "매력적인" },
        { word: "conjuncture", meaning: "결합, 접합" },
        { word: "voracious predator", meaning: "탐욕스러운 포식자" },
        { word: "at the same time", meaning: "동시에, 함께" },
        { word: "sacred", meaning: "신성한" },
        { word: "signal", meaning: "신호를 보내다" },
        { word: "conceive", meaning: "상상하다" },
        { word: "marginally", meaning: "조금" },
        { word: "unresolved", meaning: "미정의" },
        { word: "accumulate", meaning: "(서서히) 모으다" },
        { word: "trap", meaning: "잡다" },
        { word: "devise", meaning: "고안하다" },
        { word: "refuge", meaning: "피난처" },
        { word: "in addition", meaning: "게다가" },
        { word: "debris", meaning: "파편, 잔해" },
        { word: "aberrant", meaning: "정도를 벗어난" },
        { word: "immobile", meaning: "움직이지 못하는, 정지한" },
        { word: "infrequent", meaning: "드문" },
        { word: "astonish", meaning: "깜짝 놀라게 하다" },
        { word: "strikingly", meaning: "눈에 띄게" },
        { word: "hinder", meaning: "방해하다" },
        { word: "emergency", meaning: "위기, 비상 사태" },
        { word: "progressive", meaning: "진보적인, 점진적인" },
        { word: "antagonistic", meaning: "적대하는, 대립하는" },
        { word: "stringent", meaning: "엄한" },
        { word: "obliterate", meaning: "지우다" },
        { word: "ritual", meaning: "의식적인" },
        { word: "issue", meaning: "문제, 논점" },
        { word: "milestone", meaning: "획기적인 사건" },
        { word: "methodical", meaning: "체계적인" },
        { word: "updated", meaning: "최신의" },
        { word: "capacity", meaning: "능력, 재능" },
        { word: "vastly", meaning: "대단히" },
        { word: "scanty", meaning: "부족한" }
    ],
    25: [
        { word: "vulnerable", meaning: "취약한" },
        { word: "contribute", meaning: "기부하다, 공헌하다" },
        { word: "linger", meaning: "남다" },
        { word: "discard", meaning: "버리다" },
        { word: "antiquity", meaning: "고대" },
        { word: "obstacle", meaning: "장애물" },
        { word: "preserve", meaning: "보호하다, 보존하다" },
        { word: "consequent", meaning: "결과로서 일어나는" },
        { word: "universal", meaning: "전 세계적인, 보편적인" },
        { word: "timid", meaning: "소심한, 겁 많은" },
        { word: "modulate", meaning: "조절하다, 조정하다" },
        { word: "equivalent", meaning: "동등한, 상응하는" },
        { word: "elite", meaning: "최상류층" },
        { word: "lucrative", meaning: "수익성이 좋은, 유리한" },
        { word: "graduate to", meaning: "(더 높은 단계로) 나아가다, 승진하다" },
        { word: "inevitable", meaning: "불가피한" },
        { word: "yardstick", meaning: "기준, 척도" },
        { word: "hallmark", meaning: "특징" },
        { word: "stratify", meaning: "층을 이루다" },
        { word: "lessen", meaning: "줄이다" },
        { word: "endorse", meaning: "지지하다, 서명(배서)하다" },
        { word: "wrought", meaning: "만들어진" },
        { word: "severely", meaning: "격렬하게, 심하게" },
        { word: "sparsely", meaning: "드문드문, 밀도가 낮게" },
        { word: "opaque", meaning: "불분명한, 불투명한" },
        { word: "immutable", meaning: "불변의" },
        { word: "robust", meaning: "튼튼한, 강한" },
        { word: "rival", meaning: "경쟁하는, 경쟁자, ~와 경쟁하다" },
        { word: "accrete", meaning: "하나로 합쳐지다" },
        { word: "demonstrate", meaning: "나타내다, 보여주다" },
        { word: "groom", meaning: "(깔끔하게) 다듬다" },
        { word: "impending", meaning: "임박한" },
        { word: "extensive", meaning: "광범위한, 넓은" },
        { word: "innovative", meaning: "독창적인" },
        { word: "evoke", meaning: "불러일으키다" },
        { word: "prior to", meaning: "~보다 전에" },
        { word: "advent", meaning: "출현, 도래" },
        { word: "diversity", meaning: "다양성, 차이" },
        { word: "enigmatic", meaning: "불가사의한, 이해할 수 없는" },
        { word: "conviction", meaning: "(강한) 신념" },
        { word: "seemingly", meaning: "외견상으로, 겉보기에는" },
        { word: "uninterrupted", meaning: "연속적인, 끊임없는" },
        { word: "convention", meaning: "관례, 관습" },
        { word: "dampen", meaning: "적시다" },
        { word: "coincide with", meaning: "일치하다" },
        { word: "doctrine", meaning: "교리, 원칙" },
        { word: "decimation", meaning: "대량 파괴, 대량 살해" },
        { word: "complicated", meaning: "복잡한" },
        { word: "correlate", meaning: "(서로) 연관시키다" },
        { word: "dispute", meaning: "논쟁하다, 논쟁" }
    ],
    26: [
        { word: "exclusive", meaning: "유일한" },
        { word: "especially", meaning: "특히" },
        { word: "tenacity", meaning: "완고함, 고집" },
        { word: "exhaust", meaning: "다 써 버리다, 고갈시키다, 지치게 하다" },
        { word: "prerequisite", meaning: "필요 조건" },
        { word: "vacant", meaning: "(집∙땅 등이) 비어 있는" },
        { word: "premise", meaning: "전제, 가정" },
        { word: "commonly", meaning: "보통, 일반적으로" },
        { word: "probe", meaning: "조사하다, 찾다, 탐구, 탐사" },
        { word: "diligently", meaning: "열심히, 애써서" },
        { word: "assume", meaning: "(책임∙임무를) 떠맡다, 생각하다" },
        { word: "enactment", meaning: "(법률) 제정" },
        { word: "manipulate", meaning: "다루다, 조종하다, 조작하다, 속이다" },
        { word: "spark", meaning: "유발하다" },
        { word: "sensational", meaning: "굉장한, 놀라운" },
        { word: "cite", meaning: "언급하다" },
        { word: "innumerable", meaning: "무수한" },
        { word: "rare", meaning: "드문" },
        { word: "dwindle", meaning: "줄어들다" },
        { word: "anxious", meaning: "걱정하는, 열망하는" },
        { word: "convincing", meaning: "설득력 있는" },
        { word: "impede", meaning: "방해하다" },
        { word: "periodically", meaning: "정기적으로, 간헐적으로, 때때로" },
        { word: "havoc", meaning: "대파괴" },
        { word: "amplification", meaning: "부연 설명" },
        { word: "agitate", meaning: "뒤흔들다, 휘젓다" },
        { word: "naively", meaning: "솔직하게, 순진하게" },
        { word: "offset", meaning: "상쇄하다" },
        { word: "proper", meaning: "적절한" },
        { word: "immunity", meaning: "면제" },
        { word: "segregate", meaning: "분리하다, 격리하다" },
        { word: "instantaneous", meaning: "즉각적인" },
        { word: "rim", meaning: "가장자리" },
        { word: "conclude", meaning: "결론을 내리다" },
        { word: "handy", meaning: "편리한" },
        { word: "in profile", meaning: "옆모습으로" },
        { word: "distinctive", meaning: "특유의, 특색 있는" },
        { word: "require", meaning: "요구하다, 필요로 하다" },
        { word: "impose", meaning: "강요하다" },
        { word: "ongoing", meaning: "계속 진행 중인" },
        { word: "associated", meaning: "관련된" },
        { word: "primary", meaning: "기본적인" },
        { word: "interval", meaning: "(시간∙공간의) 간격, 기간" },
        { word: "collaborative", meaning: "공동의, 협력적인" },
        { word: "vague", meaning: "모호한, 불분명한" },
        { word: "locate", meaning: "(위치 등을) 찾아내다, 발견하다, (장소∙위치에) 두다" },
        { word: "insight", meaning: "통찰력, 이해" },
        { word: "jettison", meaning: "버리다" },
        { word: "creative", meaning: "창의적인" },
        { word: "humble", meaning: "초라한, 겸손한" }
    ],
    27: [
        { word: "beneficial", meaning: "유익한" },
        { word: "numerous", meaning: "매우 많은" },
        { word: "heir", meaning: "상속인" },
        { word: "in essence", meaning: "본질적으로" },
        { word: "desert", meaning: "(사람∙장소 등을) 버리다" },
        { word: "wholly", meaning: "완전히" },
        { word: "costly", meaning: "돈이 많이 드는" },
        { word: "ostentatious", meaning: "과시하는" },
        { word: "remnant", meaning: "나머지, 잔존물" },
        { word: "retrospect", meaning: "회고하다, 추억하다" },
        { word: "enduring", meaning: "지속되는, 영속적인" },
        { word: "displace", meaning: "대체하다, 옮기다" },
        { word: "undermine", meaning: "약화시키다" },
        { word: "prolong", meaning: "연장하다" },
        { word: "restrict", meaning: "제한하다" },
        { word: "diminish", meaning: "줄이다" },
        { word: "startling", meaning: "놀라운" },
        { word: "consider", meaning: "곰곰이 생각하다, 고려하다" },
        { word: "compose", meaning: "구성하다" },
        { word: "manifest", meaning: "나타내다, 명백한" },
        { word: "occasional", meaning: "가끔의" },
        { word: "unaccounted for", meaning: "설명되지 않은" },
        { word: "revolutionize", meaning: "혁신을 일으키다" },
        { word: "choose", meaning: "선택하다" },
        { word: "threaten", meaning: "위태롭게 하다" },
        { word: "norm", meaning: "규범" },
        { word: "homogenize", meaning: "동질화하다" },
        { word: "discharge", meaning: "방출하다" },
        { word: "channel", meaning: "(관심∙노력 등을) 돌리다, 쏟다" },
        { word: "encompass", meaning: "포함하다" },
        { word: "fragile", meaning: "깨지기 쉬운, 약한" },
        { word: "integrate", meaning: "통합하다" },
        { word: "concede", meaning: "인정하다, 허락하다" },
        { word: "edible", meaning: "먹을 수 있는" },
        { word: "entice", meaning: "유혹하다" },
        { word: "halt", meaning: "정지시키다" },
        { word: "indispensable", meaning: "필수적인" },
        { word: "fashion", meaning: "방식, 만들다, 형성하다" },
        { word: "scrutinize", meaning: "(세밀히) 조사하다" },
        { word: "controversial", meaning: "논쟁의 여지가 있는" },
        { word: "distribute", meaning: "분배하다" },
        { word: "defend", meaning: "방어하다, 지키다" },
        { word: "haphazard", meaning: "무계획적인, 우연한" },
        { word: "specifically", meaning: "특별히" },
        { word: "work out at", meaning: "계산되다" },
        { word: "adequate", meaning: "충분한" },
        { word: "faithful", meaning: "(사실 등에) 충실한, 정확한" },
        { word: "match", meaning: "맞먹다, 필적하다" },
        { word: "enlist", meaning: "입대하다, (신병을) 모집하다" },
        { word: "mainstay", meaning: "주요 의지물, 대들보" }
    ],
    28: [
        { word: "contract", meaning: "줄이다, 수축하다" },
        { word: "estimate", meaning: "평가하다, 추산하다" },
        { word: "promising", meaning: "유망한" },
        { word: "disintegrate", meaning: "붕괴되다" },
        { word: "monumental", meaning: "엄청나게 큰, 기념비적인" },
        { word: "significantly", meaning: "상당히" },
        { word: "delicate", meaning: "깨지기 쉬운, 섬세한" },
        { word: "instigate", meaning: "유발하다" },
        { word: "simulate", meaning: "흉내 내다, 가장하다" },
        { word: "intense", meaning: "강렬한, 극심한" },
        { word: "on the contrary", meaning: "그와는 반대로" },
        { word: "immoral", meaning: "부도덕한" },
        { word: "secrete", meaning: "분비하다, 숨기다" },
        { word: "adopt", meaning: "채택하다, 받아들이다" },
        { word: "display", meaning: "보여 주다" },
        { word: "preponderance", meaning: "대부분" },
        { word: "liken to", meaning: "~에 비유하다" },
        { word: "by virtue of", meaning: "~ 덕분에(때문에)" },
        { word: "undergo", meaning: "(변화 등을) 겪다, 경험하다" },
        { word: "divest", meaning: "빼앗다, 박탈하다" },
        { word: "concur", meaning: "동의하다" },
        { word: "conserve", meaning: "보존하다, 보호하다" },
        { word: "amplitude", meaning: "크기, 규모" },
        { word: "conclusively", meaning: "결정적으로" },
        { word: "patent", meaning: "명백한" },
        { word: "approximate", meaning: "대략적인, 가까운, 비슷하다" },
        { word: "onset", meaning: "시작" },
        { word: "resurgence", meaning: "재기, 부활" },
        { word: "regular", meaning: "정기적인, 일정한" },
        { word: "mechanism", meaning: "기계, 장치, 방법" },
        { word: "hover", meaning: "맴돌다, 떠다니다" },
        { word: "speculate", meaning: "추측하다" },
        { word: "reinforce", meaning: "강화하다" },
        { word: "witness", meaning: "목격하다" },
        { word: "relish", meaning: "즐기다" },
        { word: "toil", meaning: "힘써 일하다" },
        { word: "ominous", meaning: "불길한, 험악한" },
        { word: "hurdle", meaning: "장애물" },
        { word: "merchandise", meaning: "상품" },
        { word: "permanently", meaning: "영구히" },
        { word: "distinguish", meaning: "구별하다" },
        { word: "abundance", meaning: "다수, 풍부" },
        { word: "crisis", meaning: "위기" },
        { word: "involved", meaning: "복잡한" },
        { word: "puzzling", meaning: "영문 모를" },
        { word: "mount", meaning: "증가하다" },
        { word: "stretch", meaning: "늘이다" },
        { word: "intermingle", meaning: "섞이다" },
        { word: "confidence", meaning: "확신" },
        { word: "pacifier", meaning: "중재자" }
    ],
    29: [
        { word: "embellishment", meaning: "장식(물)" },
        { word: "seamless", meaning: "아주 매끄러운" },
        { word: "widespread", meaning: "광범위한, 널리 퍼진" },
        { word: "repercussion", meaning: "(사건∙행동 등의) 영향" },
        { word: "evolve", meaning: "(서서히) 발전하다, 진화하다" },
        { word: "dissent", meaning: "이의를 제기하다" },
        { word: "impart", meaning: "주다, 부여하다" },
        { word: "compact", meaning: "빽빽한, 작은, 압축하다" },
        { word: "elongate", meaning: "늘이다" },
        { word: "trauma", meaning: "외상, 외상성 상해" },
        { word: "out of sight", meaning: "보이지 않는 곳에" },
        { word: "collide", meaning: "충돌하다" },
        { word: "elegant", meaning: "품위 있는, 세련된" },
        { word: "surplus", meaning: "과잉, 잉여물" },
        { word: "found", meaning: "창설하다, 설립하다" },
        { word: "analogous", meaning: "유사한" },
        { word: "transition", meaning: "변화, 변천" },
        { word: "scarce", meaning: "부족한, 희귀한" },
        { word: "ambiguous", meaning: "모호한" },
        { word: "despite", meaning: "~에도 불구하고" },
        { word: "employ", meaning: "사용하다" },
        { word: "intrinsic", meaning: "고유의, 타고난" },
        { word: "assessment", meaning: "평가" },
        { word: "predominantly", meaning: "주로, 대부분" },
        { word: "perishable", meaning: "잘 상하는, 썩기 쉬운, 영속하지 않는" },
        { word: "despondent", meaning: "낙담한" },
        { word: "scope", meaning: "범위" },
        { word: "myriad", meaning: "무수히 많음, 무수한" },
        { word: "aim", meaning: "목적, 목표, 목표하다, 겨냥하다" },
        { word: "be incorporated in", meaning: "포함되다, 편입되다" },
        { word: "distant", meaning: "먼" },
        { word: "misleading", meaning: "현혹시키는" },
        { word: "shrivel", meaning: "시들다" },
        { word: "foster", meaning: "조장하다" },
        { word: "devoid of", meaning: "~이 없는, 결여된" },
        { word: "in response to", meaning: "~에 대한 대응으로" },
        { word: "relentless", meaning: "끊임없는" },
        { word: "clear", meaning: "분명한, 치우다" },
        { word: "swiftly", meaning: "빠르게" },
        { word: "in tandem with", meaning: "~와 협력하여" },
        { word: "proportion", meaning: "비율, 크기, 규모" },
        { word: "perplexed", meaning: "당혹스러운" },
        { word: "feature", meaning: "특징" },
        { word: "vital", meaning: "매우 중요한" },
        { word: "emergence", meaning: "출현" },
        { word: "projection", meaning: "추정, 예상" },
        { word: "signature", meaning: "서명" },
        { word: "from time to time", meaning: "가끔" },
        { word: "sterile", meaning: "척박한" },
        { word: "draw", meaning: "(마음∙이목 등을) 끌다" }
    ],
    30: [
        { word: "incessantly", meaning: "끊임없이" },
        { word: "instructive", meaning: "교육적인, 유익한" },
        { word: "habitat", meaning: "서식 환경, 거주지" },
        { word: "alarm", meaning: "공포, 놀라게 하다" },
        { word: "keenly", meaning: "강렬하게, 몹시" },
        { word: "suitable", meaning: "적절한" },
        { word: "assorted", meaning: "다채로운" },
        { word: "redundancy", meaning: "불필요한 중복, 과잉" },
        { word: "bountiful", meaning: "풍부한" },
        { word: "ubiquitous", meaning: "어디에나 존재하는" },
        { word: "prodigious", meaning: "막대한" },
        { word: "steadfastly", meaning: "확고하게" },
        { word: "converse", meaning: "반대의" },
        { word: "shortcoming", meaning: "결점, 단점" },
        { word: "fluctuate", meaning: "변동하다" },
        { word: "viability", meaning: "생존 능력, 실행 가능성" },
        { word: "abruptly", meaning: "갑자기" },
        { word: "abort", meaning: "중단하다" },
        { word: "antique", meaning: "고대의, 오래된" },
        { word: "distort", meaning: "왜곡하다" },
        { word: "imply", meaning: "시사하다" },
        { word: "etch", meaning: "새기다" },
        { word: "precision", meaning: "정확성" },
        { word: "pose", meaning: "(위협 등을) 가하다, 일으키다" },
        { word: "dryness", meaning: "건조" },
        { word: "entirely", meaning: "완전히" },
        { word: "dim", meaning: "희미한" },
        { word: "eminent", meaning: "뛰어난" },
        { word: "perceptibly", meaning: "눈에 띄게, 상당히" },
        { word: "embrace", meaning: "받아들이다" },
        { word: "constricted", meaning: "좁은, 죈" },
        { word: "roundabout", meaning: "우회적인, 간접적인" },
        { word: "vicinity", meaning: "주변, 인근, 근접" },
        { word: "portray", meaning: "묘사하다, 보여주다" },
        { word: "episode", meaning: "하나의 사건" },
        { word: "precarious", meaning: "불안정한" },
        { word: "elicit", meaning: "(정보∙반응 등을) 끌어내다" },
        { word: "principal", meaning: "주요한" },
        { word: "reckless", meaning: "부주의한" },
        { word: "previously", meaning: "이전에" },
        { word: "whereas", meaning: "~에 반하여" },
        { word: "subject to", meaning: "~에 영향을 받기 쉬운" },
        { word: "penchant", meaning: "경향, 기호" },
        { word: "ruthlessly", meaning: "무자비하게" },
        { word: "retard", meaning: "지체시키다" },
        { word: "intercourse", meaning: "교류, 교환" },
        { word: "artisan", meaning: "장인" },
        { word: "deter", meaning: "방해하다, 막다" },
        { word: "broaden", meaning: "넓히다" },
        { word: "efficacy", meaning: "효능" }
    ]
};

